import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import DashboardHeader from '../Dashboard/DashboardHeader';
import { jsPDF } from 'jspdf';
import { useGlobalData } from '../../context/data/DataState';

export default function Report() {
    const { reportType } = useParams();
    const { user } = useGlobalData();
    const [reportTitle, setReportTitle] = useState('');

    useEffect(() => {
        if (!reportType) return;
        const title = reportType.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        setReportTitle(title);
    }, [reportType]);

    const handleDownload = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const timestamp = new Date().toLocaleString();
        const userName = user?.email || "Unknown User";

        // 1. Watermark (Bottom Right Corner)
        doc.setTextColor(200, 200, 200); // Light Gray
        doc.setFontSize(10);
        const watermarkText = `Generated by ${userName} | ${timestamp}`;
        doc.text(watermarkText, pageWidth - 10, pageHeight - 10, { align: 'right' });

        // 2. Main Content
        doc.setTextColor(0, 0, 0); // Black
        doc.setFontSize(22);
        doc.text(`PowerByte Report: ${reportTitle}`, 20, 30);
        
        doc.setFontSize(12);
        doc.text("No last data found for the selected period.", 20, 50);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("This is an automated system report. Please contact support if you believe this is an error.", 20, 60);

        doc.save(`${reportType}_report.pdf`);
    };

    return (
        <div className="min-h-screen bg-gray-50 p-8 font-sans">
             <div className="max-w-7xl mx-auto">
                <DashboardHeader activeTab="Reports" />
                
                <div className="bg-white rounded-3xl p-12 shadow-sm text-center flex flex-col items-center justify-center min-h-[60vh]">
                    <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mb-6">
                        <span className="text-4xl">📄</span>
                    </div>
                    
                    <h2 className="text-2xl font-bold text-gray-900 mb-2">{reportTitle}</h2>
                    <p className="text-gray-500 mb-8 text-lg">No last data found for this report type.</p>

                    <button 
                        onClick={handleDownload}
                        className="flex items-center px-8 py-3 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition shadow-lg hover:shadow-xl transform hover:-translate-y-1"
                    >
                        <span className="mr-2 text-xl">⬇</span>
                        Download Report
                    </button>
                    
                    <p className="mt-4 text-xs text-gray-400">
                        Report will include timestamp and user verification.
                    </p>
                </div>
            </div>
        </div>
    );
}
