import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useGlobalData } from '../../context/data/DataState';
import { useNotification } from '../../context/NotificationContext';
import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';

const navItems = [
    { name: 'Account', path: '/panel/account' },
    { name: 'Dashboard', path: '/panel/dashboard' },
    { name: 'Energy Calculator', path: '/panel/energycalculator' },
    { name: 'zone Date', path: '/panel/zones' },
];

export default function DashboardHeader({ activeTab = 'Dashboard' }) {
    const { user, realtimePrediction, kitchen, unitRate } = useGlobalData() || {}; // Handle potential context missing
    const { notificationsEnabled, toggleNotifications } = useNotification();
    const [hovered, setHovered] = useState(null);
    const [exportDropdown, setExportDropdown] = useState(false);
    const [isHelpOpen, setIsHelpOpen] = useState(false);
    const navigate = useNavigate();

    // Check if real data is being received
    // Data is considered active if:
    // 1. Kitchen data has actual power values (RX, TX1, TX2 > 0)
    // 2. OR realtimePrediction has valid predicted_power
    const isDataActive = React.useMemo(() => {
        if (!kitchen) return false;
        
        const rxPower = kitchen['Main Receiver (RX)']?.Power || 0;
        const tx1Power = kitchen['TX1']?.Power || 0;
        const tx2Power = kitchen['TX2']?.Power || 0;
        const predictedPower = realtimePrediction?.predicted_power || 0;
        
        // Data is active if any sensor has power > 0 or prediction exists with power > 0
        return (rxPower > 0 || tx1Power > 0 || tx2Power > 0 || predictedPower > 0);
    }, [kitchen, realtimePrediction]);

    const handleLogout = () => {
        signOut(auth).then(() => {
            localStorage.removeItem('user');
            navigate('/login');
        }).catch((error) => {
            console.error("Logout Error:", error);
        });
    };

    const handleExport = (duration) => {
        setExportDropdown(false);
        const date = new Date();
        const timestamp = date.toLocaleString();
        const userName = user?.displayName || user?.email || 'Guest User';
        const docName = `PowerByte_Report_${duration.replace(/\s/g, '_')}_${date.toISOString().split('T')[0]}.csv`;

        // 1. Watermark / Header Metadata
        let csvContent = `Report Generated On,${timestamp}\n`;
        csvContent += `Generated By,${userName}\n`;
        csvContent += `Report Duration,${duration}\n`;
        csvContent += `Security Verification,POWERBYTE_SECURE_${Date.now()}\n\n`;

        // 2. Data Headers
        csvContent += `Date,Time,Active Power (W),Voltage (V),Current (A),Status\n`;

        // 3. Generate Mock Data (since we don't have a real historical DB for 5 years)
        // We will generate different amounts of rows based on duration
        let days = 30;
        if (duration === 'Quarterly Data') days = 90;
        if (duration === 'Yearly Data') days = 365;
        if (duration === '5 Years Data') days = 365 * 5;

        // Limit rows for CSV performance in browser (e.g., last 1000 points or daily avg)
        // For this demo, let's generate daily summaries
        for (let i = 0; i < days; i++) {
            const rowDate = new Date();
            rowDate.setDate(rowDate.getDate() - i);
            const dateStr = rowDate.toLocaleDateString();
            const timeStr = "12:00 PM"; // Daily Avg
            const power = (Math.random() * 2000 + 500).toFixed(2);
            const voltage = (220 + Math.random() * 20).toFixed(1);
            const current = (power / voltage).toFixed(2);
            const status = power > 2000 ? 'High Load' : 'Normal';

            csvContent += `${dateStr},${timeStr},${power},${voltage},${current},${status}\n`;
        }

        // 4. Trigger Download
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        if (link.download !== undefined) {
            const url = URL.createObjectURL(blob);
            link.setAttribute('href', url);
            link.setAttribute('download', docName);
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    };

    return (
        <div className="flex flex-col space-y-6 mb-8">
            {/* Top Navigation Bar & Action Area */}
            <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
                {/* Navigation Pills */}
                <div className="bg-[#1a237e] rounded-full p-1 flex space-x-1 shadow-lg overflow-x-auto max-w-full no-scrollbar">
                    {navItems.map((item) => (
                        <Link
                            key={item.name}
                            to={item.path}
                            onMouseEnter={() => setHovered(item.name)}
                            onMouseLeave={() => setHovered(null)}
                            className={`
                                relative px-4 md:px-6 py-2 rounded-full text-xs md:text-sm font-semibold transition-all duration-300 whitespace-nowrap
                                ${activeTab === item.name
                                    ? 'bg-[#4caf50] text-white shadow-md transform scale-105'
                                    : 'text-gray-300 hover:text-white'}
                            `}
                        >
                            {activeTab === item.name && (
                                <span className="absolute inset-0 bg-white/10 rounded-full animate-pulse" />
                            )}
                            {item.name}
                        </Link>
                    ))}
                </div>

                {/* Search, Icons, Sign Out */}
                <div className="flex flex-wrap justify-center items-center gap-3 w-full md:w-auto">
                    <div className="relative flex-grow md:flex-grow-0">
                        <input
                            type="text"
                            placeholder="Search..."
                            className="w-full md:w-48 pl-4 pr-8 py-1.5 rounded-full border border-gray-300 text-sm focus:outline-none focus:ring-2 focus:ring-[#4caf50] shadow-sm"
                        />
                        <span className="absolute right-3 top-2 text-gray-400 text-xs">🔍</span>
                    </div>

                    <div className="flex items-center space-x-2">
                        {/* Help Icon */}
                        <button
                            onClick={() => setIsHelpOpen(true)}
                            className="relative p-2 text-gray-400 hover:text-indigo-600 transition-colors bg-white rounded-xl border border-gray-100 shadow-sm"
                            title="Formulas & Logic"
                        >
                            <span className="text-xl">❓</span>
                        </button>

                        {/* Notification Bell - Interactive Toggle */}
                        <button
                            onClick={toggleNotifications}
                            className={`
                                p-2 rounded-full transition-all shadow-sm relative
                                ${notificationsEnabled 
                                    ? 'bg-green-50 text-green-600 hover:bg-green-100' 
                                    : 'bg-gray-100 text-gray-400 hover:bg-gray-200'}
                            `}
                            title={notificationsEnabled ? 'Notifications enabled' : 'Notifications disabled'}
                            aria-label={notificationsEnabled ? 'Disable notifications' : 'Enable notifications'}
                            aria-pressed={notificationsEnabled}
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                            </svg>
                            
                            {/* Off Badge */}
                            {!notificationsEnabled && (
                                <div className="absolute -top-1 -right-1 w-4 h-4 bg-red-500 rounded-full flex items-center justify-center">
                                    <svg className="w-2.5 h-2.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </div>
                            )}
                        </button>
                        <button className="p-2 rounded-full bg-green-50 text-green-600 hover:bg-green-100 transition shadow-sm">
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" /></svg>
                        </button>
                    </div>

                    <button
                        onClick={handleLogout}
                        className="flex items-center space-x-1 px-4 py-1.5 rounded-full bg-red-50 text-red-600 hover:bg-red-100 text-sm font-semibold transition shadow-sm border border-red-100"
                    >
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                        </svg>
                        <span className="hidden sm:inline">Sign Out</span>
                        <span className="sm:hidden">Exit</span>
                    </button>
                </div>
            </div>

            {/* Title & Date Section */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end space-y-4 md:space-y-0">
                <div className="text-center md:text-left w-full md:w-auto">
                    <h1 className="text-2xl md:text-3xl font-black text-gray-900 tracking-tight uppercase">POWERBYTE PANEL</h1>
                    <p className="text-gray-500 font-medium text-sm md:text-base">
                        Today is {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                    </p>
                    {/* Live Status Indicator */}
                    <div className="flex items-center mt-2 space-x-2">
                        <span className={`relative flex h-3 w-3`}>
                            <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${isDataActive ? 'bg-green-400' : 'bg-red-400'}`}></span>
                            <span className={`relative inline-flex rounded-full h-3 w-3 ${isDataActive ? 'bg-green-500' : 'bg-red-500'}`}></span>
                        </span>
                        <span className={`text-xs font-bold tracking-wide uppercase ${isDataActive ? 'text-green-600' : 'text-red-500'}`}>
                            {isDataActive ? 'ACTIVE' : 'INACTIVE'}
                        </span>
                        <span className="text-xs text-gray-400">
                            {isDataActive ? '— Realtime data updating' : '— No realtime data'}
                        </span>
                    </div>
                </div>

                <div className="relative w-full md:w-auto">
                    <button
                        onClick={() => setExportDropdown(!exportDropdown)}
                        className="w-full md:w-auto justify-center bg-black text-white px-6 py-2 rounded-lg text-sm font-semibold hover:bg-gray-800 transition shadow-lg flex items-center"
                    >
                        Export Report
                        <svg className={`ml-2 w-4 h-4 transition-transform ${exportDropdown ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                        </svg>
                    </button>

                    {exportDropdown && (
                        <div className="absolute right-0 left-0 md:left-auto mt-2 w-full md:w-48 bg-white rounded-xl shadow-xl z-50 border border-gray-100 overflow-hidden">
                            <div className="py-1">
                                {['Monthly Data', 'Quarterly Data', 'Yearly Data', '5 Years Data'].map((option) => (
                                    <button
                                        key={option}
                                        className="block w-full text-left px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 hover:text-indigo-600 transition-colors"
                                        onClick={() => handleExport(option)}
                                    >
                                        {option}
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>
            {/* Help Modal */}
            {isHelpOpen && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-2xl p-8 w-full max-w-lg shadow-2xl relative">
                        <button
                            onClick={() => setIsHelpOpen(false)}
                            className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 text-xl font-bold"
                        >
                            ×
                        </button>

                        <div className="flex items-center gap-3 mb-6">
                            <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center text-2xl">
                                💡
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900">PowerByte Logic</h3>
                                <p className="text-sm text-gray-500">How we calculate your metrics</p>
                            </div>
                        </div>

                        <div className="space-y-6">
                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h4 className="font-bold text-gray-700 text-sm mb-2 uppercase tracking-wider">Power & Energy</h4>
                                <div className="space-y-3">
                                    <div className="flex justify-between items-center text-sm">
                                        <span className="text-gray-600">Power (P)</span>
                                        <span className="font-mono bg-white px-2 py-1 rounded border border-gray-200 text-indigo-600">P (W) = V × I</span>
                                    </div>
                                    <div className="flex justify-between items-center text-sm">
                                        <span className="text-gray-600">Energy (E)</span>
                                        <span className="font-mono bg-white px-2 py-1 rounded border border-gray-200 text-indigo-600">E (kWh) = (P × t) / 1000</span>
                                    </div>
                                </div>
                            </div>

                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h4 className="font-bold text-gray-700 text-sm mb-2 uppercase tracking-wider">Sustainability & Cost</h4>
                                <div className="space-y-3">
                                    <div className="flex justify-between items-center text-sm">
                                        <span className="text-gray-600">Carbon Emission</span>
                                        <div className="text-right">
                                            <span className="font-mono bg-white px-2 py-1 rounded border border-gray-200 text-emerald-600 block">E × 0.716</span>
                                            <span className="text-[10px] text-gray-400 mt-1 block">CEA India 2024 Factor (kg CO₂/kWh)</span>
                                        </div>
                                    </div>
                                    <div className="flex justify-between items-center text-sm">
                                        <span className="text-gray-600">Total Cost</span>
                                        <div className="text-right">
                                            <span className="font-mono bg-white px-2 py-1 rounded border border-gray-200 text-amber-600 block">E × ₹{unitRate || 7.85}</span>
                                            <span className="text-[10px] text-gray-400 mt-1 block">Based on your tariff setting</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="mt-8 text-center">
                            <button
                                onClick={() => setIsHelpOpen(false)}
                                className="w-full bg-indigo-600 text-white py-3 rounded-xl font-bold hover:bg-indigo-700 transition"
                            >
                                Got it!
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
